### ISSUE TITLE
iPhone retina4 not sized properly

### ISSUE THREAD

**Issue by interianow** [rhdeck/react-native-launchimages#1]
### Description
I see the following warning in `Images.xcassets`

<img width="474" alt="screen shot 2018-06-28 at 3 06 04 pm" src="https://user-images.githubusercontent.com/29824849/42055439-21a1210e-7ae5-11e8-8299-161e90958e3d.png">

There are 2 definitions for iPhone retina4 in `contents.json` where 1 definition is the wrong dimensions and 1 definition is the correct dimensions that Xcode wants.

**Comment by rimiti** [comment]
+1

**Comment by rhdeck** [comment]
Resolved in 1.0.1
